### ISSUE TITLE
Поддержка PostgreSQL через ODBC

### ISSUE THREAD

**Issue by RIS2000** [alex-bochkov/PasswordChanger1C#11]
Здравствуйте, Алексей!

Спасибо за хороший инструмент, во многих случаях он очень полезен.
Я попытался модифицировать программу для работы с PostgreSQL через ODBC.
На чтение получилось, но никак не могу сделать update, не получается с байтовыми полями.
Может у вас есть желание посотрудничать по этому вопросу ?
Если да, то куда выложить доработки ?

**Comment by alex-bochkov** [comment]
@RIS2000 - создайте, пожалуйста, тут бранч со своими доработками и pull request в master.
Спасибо!

**Comment by RIS2000** [comment]
Получение из origin
From https://github.com/alekseybochkov/PasswordChanger1C
 = [up to date]      master     -> origin/master
Отправка ris_postgresql
Произошла ошибка при отправке ветви в удаленный репозиторий: Git failed with a fatal error.
unable to access 'https://github.com/alekseybochkov/PasswordChanger1C/': The requested URL returned error: 403
Pushing to https://github.com/alekseybochkov/PasswordChanger1C

каких то прав не хватает видимо ?

**Comment by nixel2007** [comment]
Вам нужно сделать форк и отправлять в него, а не в текущий репозиторий.

**Comment by alex-bochkov** [comment]
@RIS2000 попробуйте эту версию, пожалуйста - https://github.com/alekseybochkov/PasswordChanger1C/releases/tag/2.1.0.1

**Comment by RIS2000** [comment]
> 
> 
> @RIS2000 попробуйте эту версию, пожалуйста - https://github.com/alekseybochkov/PasswordChanger1C/releases/tag/2.1.0.1

Работает!
Спасибо!
